# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: SOAP-Library

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: pip install -r requirements-dev.txt

    - name: Ensure Code Formatting
      run: inv lint

    - name: Run Robot Tests
      run: |
        coverage run -m invoke test
        coverage report

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Test Results ${{ matrix.os }}
        path: |
          log.html
          output.xml
          report.html
